apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-devops
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:latest
          imagePullPolicy: Always
          livenessProbe:
            periodSeconds: 5
            initialDelaySeconds: 10
            failureThreshold: 3
            httpGet:
              port: 80
          ports:
            - containerPort: 80