version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/cms
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/website
    schedule:
      interval: weekly
