enableGlobalCache: true
enableTelemetry: false
nmHoistingLimits: workspaces
nodeLinker: node-modules
preferAggregateCacheInfo: true
yarnPath: ".yarn/releases/yarn-berry.cjs"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

