yarnPath: .yarn/releases/yarn-3.1.0.cjs
enableGlobalCache: true
enableTelemetry: false
preferAggregateCacheInfo: true
nmHoistingLimits: workspaces
nodeLinker: node-modules
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard