enableGlobalCache: true
enableTelemetry: false
nodeLinker: node-modules
nmHoistingLimits: workspaces
preferAggregateCacheInfo: true
yarnPath: ".yarn/releases/yarn-berry.cjs"
plugins:
- path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  spec: "@yarnpkg/plugin-workspace-tools"
