changesetBaseRefs:
  - latest
  - origin/latest

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0007
    level: discard

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nmSelfReferences: false

nodeLinker: node-modules

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.21.git.20220926.hash-8ff27df.cjs
