version: '3.x'

networks:
  public:
  private:

volumes:
  database:
  pki:
  caddy:

services:

  # This container handles external traffic on HTTP/HTTPS, handing routes inside of Caddyfile config.
  proxy:
    container_name: proxy
    image: caddy/caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    networks:
      - public
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - pki:/data/caddy
      - caddy:/config
    env_file:
      - .env

  website:
    container_name: website
    build:
      target: website
    image: website:${APP_VERSION:-latest}
    networks:
      - public

  cms:
    container_name: cms
    build:
      target: cms
    image: cms:${APP_VERSION:-latest}
    networks:
      - public
      - private
    env_file:
      - .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: database

  database:
    container_name: database
    image: postgres:14.3
    networks:
      - private
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql
      - ./packages/cms/database/dumps:/docker-entrypoint-initdb.d:ro
