version: '3.x'

volumes:
  database:

services:
  traeffik:
    image: traefik:v3.0
    command:
      #      - '--certificatesresolvers.letsencrypt.acme.email=admin@$DOMAIN'
      #      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      #      - '--certificatesresolvers.letsencrypt.acme.storage=acme.json'
      #      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker=true'
    #    volumes:
    #      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'

  website:
    #    build:
    #      args:
    #        api_url: $DOMAIN/graphql
    #      target: website
    image: ${DOCKER_REPOSITORY}/app:${APP_VERSION:-latest}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.website.entrypoints: 'http'
      traefik.http.routers.website.rule: 'Host(`app.aws.bndigital.dev`)'
  #      traefik.http.routers.website.tls.certresolver: 'letsencrypt'
  #      traefik.http.routers.website.tls.domains[0].main: '$DOMAIN'
  #      traefik.http.routers.website.tls: 'true'

  database:
    image: postgres:15.1
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql
#      - ./packages/cms/database/dumps:/docker-entrypoint-initdb.d:ro
