schema: packages/cms/src/graphql/schema.graphql
exclude: packages/cms/src/graphql/extension.graphql
extensions:
  endpoints:
    development:
      url: http://127.0.0.1:1337/graphql
    staging:
      url: https://project-templates.bndigital.dev/graphql
