repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  kubeContext: do-fra1-bndigital
  createNamespace: true
  cleanupOnFail: true

environments:
  staging:
    values: []

releases:
  - name: '{{project.name}}-react'
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: react
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'

  - name: '{{project.name}}-vue'
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: vue
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'

  - name: '{{project.name}}-html'
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: html
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'

  - name: '{{project.name}}-strapi'
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: strapi
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
      - envSecrets: [ backend-services ]
        configMapsSecrets: [ backend-services ]

  - name: '{{project.name}}-{{packages.backend}}'
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: graphql
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
      - image: apisguru/graphql-faker
        app:
          port: 9092

  - name: app-storybook
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: storybook
    installed: false
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
