repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  kubeContext: do-fra1-bndigital
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-react
    namespace: staging
    chart: bndigital/nodejs
    values:
      - image: dcr.bndigital.dev/app/react:latest
        imagePullSecrets: [ container-registry ]
        ingress:
          enabled: true
          tls: true
          host: react.bndigital.dev

  - name: app-vue
    namespace: staging
    chart: bndigital/nodejs
    values:
      - image: dcr.bndigital.dev/app/vue:latest
        imagePullSecrets: [ container-registry ]
        ingress:
          enabled: true
          tls: true
          host: vue.bndigital.dev

  - name: app-landing
    namespace: staging
    chart: bndigital/nodejs
    values:
      - image: dcr.bndigital.dev/app/landing:latest
        imagePullSecrets: [ container-registry ]
        ingress:
          enabled: true
          tls: true
          host: landing.app.bndigital.dev

  - name: app-cms
    namespace: staging
    chart: bndigital/nodejs
    values:
      - image: dcr.bndigital.dev/app/cms:latest
        imagePullSecrets: [ container-registry ]
        envSecrets: [ backend-services ]
        configMapsSecrets: [ backend-services ]
        app:
          port: 1337
        ingress:
          enabled: true
          tls: true
          host: cms.app.bndigital.dev

  - name: app-storybook
    namespace: staging
    installed: false
    chart: bndigital/nodejs
    values:
      - image: dcr.bndigital.dev/app/storybook:latest
        imagePullSecrets: [ container-registry ]
        ingress:
          enabled: true
          tls: true
          host: storybook.app.bndigital.dev
