repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

environments:
  staging: { }
  production: { }

releases:
  - name: app-website
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/app
    version: 1.1.4
    labels:
      component: website
    values:
      - image: '{{ env "SKAFFOLD_DEFAULT_REPO" | default "dcr.bndigital.dev/app" }}/website:{{ env "IMAGE_TAG" | default "latest" }}'
        serviceAccount:
          name: bndigital-app
        podAnnotations:
          github.com/ref: '{{ requiredEnv "GITHUB_REF" }}'
          github.com/sha: '{{ requiredEnv "GITHUB_SHA" }}'
        ingress:
          host: '{{ env "DOMAIN" | default "app.bndigital.dev" }}'
          proxy:
            paths:
              - pathTemplate: strapi
                service:
                  name: app-cms-app

  - name: app-cms
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/app
    version: 1.1.4
    labels:
      component: website
    values:
      - image: '{{ env "SKAFFOLD_DEFAULT_REPO" | default "dcr.bndigital.dev/app" }}/cms:{{ env "IMAGE_TAG" | default "latest" }}'
        serviceAccount:
          name: bndigital-app
        podAnnotations:
          github.com/ref: '{{ requiredEnv "GITHUB_REF" }}'
          github.com/sha: '{{ requiredEnv "GITHUB_SHA" }}'