helmfiles:
  - path: git::https://github.com/bn-digital/helm.git@helmfiles/load-balancer.yaml?ref=latest
  - path: git::https://github.com/bn-digital/helm.git@helmfiles/nodejs.yaml?ref=latest

helmDefaults:
  createNamespace: true
  cleanupOnFail: true
  historyMax: 3
  timeout: 300
  waitForJobs: false

environments:
  default:
    values:
    - tlsIssuer:
        enabled: false
      ingressController:
        enabled: false
      database:
        enabled: false
  staging:
    values:
      - tlsIssuer:
          enabled: true
        ingressController:
          enabled: false
        database:
          enabled: false
  production:
    values:
      - tlsIssuer:
          enabled: true
        ingressController:
          enabled: true
        database:
          enabled: true
