repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: '{{ env "APP_NAME" | default "app" }}-website'
    namespace: '{{ env "APP_ENV" | default "staging" }}'
    chart: bndigital/app
    version: 1.1.4
    installed: true
    values:
      - image: '{{ env "DOCKER_REGISTRY" | default "dcr.bndigital.dev" }}/{{ env "APP_NAME" | default "app" }}/website:{{ env "IMAGE_TAG" | default "latest" }}'
        pullPolicy: Always
        podAnnotations:
          github.com/commit: '{{ env "GITHUB_SHA" | default "-" }}'
        serviceAccount:
          name: bndigital-app
        ingress:
          host: '{{ env "DOMAIN" | default "" }}'
          proxy:
            paths:
              - pathTemplate: strapi
                service:
                # name: %project-name%-cms-app
                  name: '{{ env "APP_NAME" | default "app" }}-cms-app'

  # name: %project-name%-cms-app
  - name: '{{ env "APP_NAME" | default "app" }}-cms'
    namespace: '{{ env "APP_ENV" | default "staging" }}'
    chart: bndigital/app
    installed: true
    version: 1.1.4
    values:
      - image: '{{ env "DOCKER_REGISTRY" | default "dcr.bndigital.dev" }}/{{ env "APP_NAME" | default "app" }}/cms:{{ env "IMAGE_TAG" | default "latest" }}'
        pullPolicy: Always
        podAnnotations:
          github.com/commit: '{{ env "GITHUB_SHA" | default "-" }}'
        serviceAccount:
          name: bndigital-app