helmDefaults:
  createNamespace: true
  cleanupOnFail: true

environments:
  staging:
    kubeContext: do-fra1-bndigital
    values: [ ]

releases:
  - name: app-website
    namespace: '{{ .Environment.Name }}'
    installed: false
    chart: packages/website
    labels:
      app: website

  - name: app-cms
    namespace: '{{ .Environment.Name }}'
    installed: false
    chart: packages/cms
    labels:
      app: cms
    
