repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

environments:
  staging: { }
  production: { }

releases:
  - name: app-website
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/app
    version: 1.0.1
    values:
      - image: '{{ env "SKAFFOLD_DEFAULT_REPO" | default "dcr.bndigital.dev/app" }}/website:{{ env "IMAGE_TAG" | default "latest" }}'
        serviceAccount:
          name: bndigital-app
        ingress:
          host: '{{ env "DOMAIN" | default "app.bndigital.dev" }}'
          proxy:
            enabled: true
            implementation: strapi
            backend:
              service: app-cms-app

  - name: app-cms
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/app
    version: 1.0.1
    values:
      - image: '{{ env "SKAFFOLD_DEFAULT_REPO" | default "dcr.bndigital.dev/app" }}/cms:{{ env "IMAGE_TAG" | default "latest" }}'
        serviceAccount:
          name: bndigital-app
