helmfiles:
  - path: git::https://github.com/bn-digital/helm.git@helmfiles/app.yaml?ref=latest

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

environments:
  default:
    values: []
  staging:
    values: []
  production:
    values: []

