repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  kubeContext: do-fra1-bndigital
  createNamespace: true
  cleanupOnFail: true

environments:
  {{cookiecutter.environment}}:
  values: [ ]

releases:
  - name: "{{cookiecutter.project.name}}-{{cookiecutter.packages.react}}"
    namespace: "{{cookiecutter.kubernetes.namespace}}"
    chart: bndigital/nodejs
    labels:
      app: "{{cookiecutter.packages.react}}"
    values:
      - "values.{{cookiecutter.environment}}.gotmpl"
        ingress:
          enabled: true
          tls: true
          host: "{{cookiecutter.packages.react}}.{{cookiecutter.kubernetes.domain}}"

  - name: "{{cookiecutter.project.name}}-{{cookiecutter.packages.vue}}"
    namespace: "{{cookiecutter.environment}}"
    chart: bndigital/nodejs
    labels:
      app: "{{cookiecutter.packages.vue}}"
    values:
      - "values.{{cookiecutter.environment}}.gotmpl"
        ingress:
          enabled: true
          tls: true
          host: "{{cookiecutter.packages.vue}}.{{cookiecutter.kubernetes.vue}}"

  - name: "{{cookiecutter.project.name}}-{{cookiecutter.packages.html}}"
    namespace: "{{cookiecutter.environment}}"
    chart: bndigital/nodejs
    labels:
      app: "{{cookiecutter.packages.html}}"
    values:
      - "values.{{cookiecutter.environment}}.gotmpl"
        ingress:
          enabled: true
          tls: true
          host: "{{cookiecutter.packages.html}}.{{cookiecutter.kubernetes.domain}}"

  - name: "{{cookiecutter.project.name}}-{{cookiecutter.packages.strapi}}"
    namespace: "{{cookiecutter.environment}}"
    chart: bndigital/nodejs
    labels:
      app: "{{cookiecutter.packages.strapi}}"
    values:
      - "values.{{cookiecutter.environment}}.gotmpl"
      - envSecrets: [ backend-services ]
        configMapsSecrets: [ backend-services ]
        ingress:
          enabled: true
          tls: true
          host: "{{cookiecutter.packages.strapi}}.{{cookiecutter.kubernetes.domain}}"

  - name: "{{cookiecutter.project.name}}-{{cookiecutter.packages.apollo}}"
    namespace: {{cookiecutter.environment}}
    chart: bndigital/nodejs
    labels:
      app: "{{cookiecutter.packages.apollo}}"
    values:
      - "values.{{cookiecutter.environment}}.gotmpl"
      - image: apisguru/graphql-faker
        app:
          port: 9092
        ingress:
          enabled: true
          tls: true
          host: "{{cookiecutter.packages.apollo}}.{{cookiecutter.kubernetes.domain}}"

  - name: "{{cookiecutter.project.name}}-{{cookiecutter.packages.storybook}}"
    namespace: "{{cookiecutter.environment}}"
    chart: bndigital/nodejs
    labels:
      app: "{{cookiecutter.packages.storybook}}"
    installed: false
    values:
      - "values.{{cookiecutter.environment}}.gotmpl"
        ingress:
          enabled: true
          tls: true
          host: "{{cookiecutter.packages.storybook}}.{{cookiecutter.kubernetes.domain}}"
