# nonk8s
---
apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: app
  tagPolicy:
    sha256:  {}
  local:
    useDockerCLI: true
    useBuildkit: true
profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
