# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    useBuildkit: true
    useDockerCLI: true
    push: false
    concurrency: 0
  tagPolicy:
    sha256: { }
  artifacts:
    - image: cms
      docker:
        target: cms
    - image: website
      docker:
        target: website

test:
  - image: website
    structureTests:
      - nodejs-container-tests.yaml
      - website-container-tests.yaml
  - image: cms
    structureTests:
      - nodejs-container-tests.yaml
      - cms-container-tests.yaml

profiles:
  - name: development
    activation:
      - kubeContext: minikube
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true