# nonk8s
---
apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - image: app
      sync:
        auto: true
        manual:
          - dest: /usr/local/src
            src: packages/cms/dist
          - dest: /usr/local/src/public
            src: packages/website/builds
  tagPolicy:
    sha256: { }
  local:
    useDockerCLI: true
    useBuildkit: true
portForward:
  - localPort: 5000
    port: 5000
    resourceName: app
test:
  - image: app
    structureTests:
      - container-structure-test.yaml
profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
