# nonk8s
---
apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    - image: app
  tagPolicy:
    sha256: { }
  local:
    useBuildkit: true
test:
  - image: app
    structureTests:
      - container-structure-test.yaml
profiles:
  - name: staging
    activation:
      - env: CI=true
    build:
      tagPolicy:
        sha256: { }
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
deploy:
  docker:
    images:
      - app
