# nonk8s
apiVersion: skaffold/v2beta25
kind: Config
build:
  local:
    concurrency: 0
    useBuildkit: true
  tagPolicy:
    sha256: {}
  artifacts:
    - image: cms
      context: packages/cms
    - image: website
      context: packages/website
profiles:
  - name: staging
    build:
      local:
        push: true
        concurrency: 0
        useBuildkit: true
