# nonk8s
---
apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
    - image: app
      docker:
        target: runtime
  tagPolicy:
    sha256: {}
profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true

