# nonk8s
---
apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: runtime
      docker:
        target: runtime
test:
  - image: website
    structureTests:
      - nodejs-container-tests.yaml
      - website-container-tests.yaml
  - image: cms
    structureTests:
      - nodejs-container-tests.yaml
      - cms-container-tests.yaml

profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
