# nonk8s
---
apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - image: app
  tagPolicy:
    sha256: { }
  local:
    useDockerCLI: true
    useBuildkit: true
profiles:
  - name: staging
    activation:
      - env: CI=true
    build:
      tagPolicy:
        inputDigest: {}
    test:
      - image: app
        structureTests:
          - container-structure-test.yaml
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
