# nonk8s
apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    - image: app
  local:
    useBuildkit: true
test:
  - image: app
    structureTests: [container-structure-test.yaml]
deploy:
  docker:
    images: [app]
portForward:
  - port: 5000
    resourceName: app
    address: 127.0.0.1
    resourceType: Container
