# nonk8s
---
apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: app
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    push: false
profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true

