name: bn-app
region: fra
services:
  - name: cms
    environment_slug: node-js
    source_dir: /
    build_command: yarn workspace @app/cms run build
    run_command: yarn workspace @app/cms run serve
    github:
      repo: bn-digital/project-templates
      branch: latest
      deploy_on_push: true
    http_port: 1337
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /cms
  - name: website
    source_dir: /
    environment_slug: node-js
    build_command: yarn workspace @app/website run build
    run_command: yarn workspace @app/website run serve
    github:
      repo: bn-digital/project-templates
      branch: latest
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5000
    routes:
      - path: /
