{{- range .Values.imagePullSecrets }} {{ if .credentials }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name }}
  labels: {{ include "nodejs.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data: {{ with .credentials }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }} {{ end }} {{ end }}
{{ end }}

