apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: "{{cookiecutter.project.name}}"
build:
  artifacts:
    - image: "{{cookiecutter.packages.vue}}"
      context: "packages/{{cookiecutter.packages.vue}}"
    - image: "{{cookiecutter.packages.html}}"
      context: "packages/{{cookiecutter.packages.html}}"
    - image: "{{cookiecutter.packages.react}}"
      context: "packages/{{cookiecutter.packages.react}}"
    - image: "{{cookiecutter.packages.strapi}}"
      context: "packages/{{cookiecutter.packages.strapi}}"
    - image: "{{cookiecutter.packages.storybook}}"
      context: "packages/{{cookiecutter.packages.storybook}}"
    - image: "{{cookiecutter.packages.apollo}}"
      context: "packages/{{cookiecutter.packages.apollo}}"
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    push: false
    useBuildkit: true
test:
  - image: "{{cookiecutter.packages.vue}}"
    custom:
      - command: "hadolint packages/{{cookiecutter.packages.vue}}/Dockerfile"
    structureTests:
      - container-structure-test.yaml
  - image: "{{cookiecutter.packages.react}}"
    custom:
      - command: "hadolint packages/{{cookiecutter.packages.react}}/Dockerfile"
    structureTests:
      - container-structure-test.yaml
  - image: "{{cookiecutter.packages.html}}"
    custom:
      - command: "hadolint packages/{{cookiecutter.packages.html}}/Dockerfile"
    structureTests:
      - container-structure-test.yaml
  - image: "{{cookiecutter.packages.strapi}}"
    custom:
      - command: "hadolint packages/{{cookiecutter.packages.strapi}}/Dockerfile"
    structureTests:
      - container-structure-test.yaml
  - image: "{{cookiecutter.packages.storybook}}"
    custom:
      - command: "hadolint packages/{{cookiecutter.packages.storybook}}/Dockerfile"
    structureTests:
      - container-structure-test.yaml
profiles:
  - name: ci
    activation:
      - kubeContext: do-fra1-bndigital
    build:
      local:
        push: false
        useBuildkit: true
