name: Analyze source code
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true

jobs:
  sonarqube:
    name: Analyze source code
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ secrets.VAULT_ENDPOINT }}
          githubToken: ${{ secrets.GH_TOKEN }}
          secrets: |
            infrastructure/data/sonarqube   host    | SONAR_HOST ;
            infrastructure/data/sonarqube   token   | SONAR_TOKEN ;

      - name: Run Sonar scanner
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          args: |
            -Dsonar.projectName=${{ inputs.project }}
            -Dsonar.projectKey=${{ inputs.project }}
            -Dsonar.links.scm=https://github.com/${{ github.repository }}
            -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions
