name: Build
on:
  release:
    types:
      - unpublished
  push:
    branches-ignore:
      - latest
    paths:
      - .github/workflows/build.yml
      - package.json
      - packages/*/package.json
      - packages/*/src/**/*
      - packages/*/public/**/*
jobs:
  build:
    name: Build app
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=path::$(yarn config get cacheFolder)"
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Yarn
        run: npm install --global yarn
      - uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.yarn-cache-dir.outputs.path }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Run linters
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run tests
        run: yarn build
