name: Build React
on:
  push:
    branches:
      - latest
    paths:
      - packages/cms/api/**/*
      - packages/cms/components/**/*
      - packages/cms/config/**/*
      - packages/cms/extensions/**/*
      - packages/cms/package.json

env:
  docker_buildkit: 1
  docker_repository: ${{ secrets.docker_registry }}/app
  docker_image: cms

jobs:
  docker:
    name: Build Strapi image
    runs-on: self-hosted
    steps:
      - name: Setup builder
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.docker_registry }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: packages/${{ env.docker_image }}
          file: packages/${{ env.docker_image }}/Dockerfile
          cache-from: type=registry,ref=${{ env.docker_repository }}/${{ env.docker_image }}
          cache-to: type=inline
          tags: ${{ env.docker_repository }}/${{ env.docker_image }}:latest
