name: Build
on:
  release:
    types:
      - unpublished
  push:
    branches-ignore:
      - latest
    paths:
      - .github/workflows/build.yml
      - package.json
      - src/**/*
      - public/**/*
jobs:
  build:
    name: Build app
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Run linters
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run tests
        run: yarn build
