name: Continuous Deployment
on:
  push:
    branches:
      - latest
      - main
      - master
    paths:
      - ".github/workflows/continuous-deployment.yml"
      - "skaffold.yaml"
      - "helmfile.*"
      - "**/*/.env.*"
      - "Dockerfile"
      - ".dockerignore"
      - "yarn.lock"
      - "packages/website/public/**/*"
      - "packages/website/src/**/*"
      - "packages/cms/config/**/*"
      - "packages/cms/database/**/*"
      - "packages/cms/public/**/*"
      - "packages/cms/src/**/*"

jobs:
  deploy:
    uses: bn-digital/project-templates/.github/workflows/deploy-charts.yml@latest
    secrets: inherit