name: Continuous Deployment
on:
  push:
    branches:
      - latest
      - main
      - master
    paths:
      - '.github/workflows/continuous-deployment.yml'
      - 'skaffold.yaml'
      - 'helmfile.*'
      - '**/*/.env.*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'yarn.lock'
      - 'packages/website/public/**/*'
      - 'packages/website/src/**/*'
      - 'packages/cms/config/**/*'
      - 'packages/cms/database/**/*'
      - 'packages/cms/public/**/*'
      - 'packages/cms/src/**/*'

jobs:
  secrets:
    uses: bn-digital/vault/.github/workflows/import-secrets.yml@latest
    secrets: inherit
  deploy:
    needs: [ secrets ]
    uses: bn-digital/helm/.github/workflows/deploy-charts.yml@latest
    secrets: inherit
  test:
    needs: [ deploy ]
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install website dependencies
        run: yarn

      - name: Run website e2e tests
        run: yarn test
        working-directory: packages/website
        env:
          DOMAIN: ${{ github.repository }}.bndigital.dev


