name: Continuous Deployment
on:
  push:
    branches:
      - latest
      - main
      - master
    paths:
      - '.github/workflows/continuous-deployment.yml'
      - 'skaffold.yaml'
      - 'helmfile.*'
      - '**/*/.env.*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'yarn.lock'
      - 'packages/website/public/**/*'
      - 'packages/website/src/**/*'
      - 'packages/cms/config/**/*'
      - 'packages/cms/database/**/*'
      - 'packages/cms/public/**/*'
      - 'packages/cms/src/**/*'

jobs:
  secrets:
    uses: bn-digital/vault/.github/workflows/import-secrets.yml@latest
    secrets: inherit
  deploy:
    needs: [ secrets ]
    uses: bn-digital/helm/.github/workflows/deploy-charts.yml@latest
    secrets: inherit
  test:
    needs: [ deploy ]
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        uses: docker/build-push-action@v3
        env:
          APP_ENV: staging
          APP_NAME: ${{ github.event.repository.name }}
        with:
          context: .
          push: false
          target: test
          tags: ${{ github.event.repository.name }}/website:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}/website:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}/website:latest,mode=max