name: Continuous Integration
on:
  pull_request:
    branches:
      - latest
      - main
      - master
    paths:
      - ".github/workflows/continuous-deployment.yml"
      - "skaffold.yaml"
      - "helmfile.*"
      - "**/*/.env.*"
      - "Dockerfile"
      - ".dockerignore"
      - "yarn.lock"
      - "packages/website/public/**/*"
      - "packages/website/src/**/*"
      - "packages/cms/config/**/*"
      - "packages/cms/database/**/*"
      - "packages/cms/public/**/*"
      - "packages/cms/src/**/*"

jobs:
  analyze:
    uses: bn-digital/project-templates/.github/workflows/analyze-code.yml@latest
    secrets: inherit
  build:
    uses: bn-digital/project-templates/.github/workflows/build-images.yml@latest
    secrets: inherit
