name: Continuous Delivery
on:
  push:
    tags:
      - '*'

jobs:
  provision:
    uses: bn-digital/terraform/.github/workflows/provision-infrastructure.yml@latest
    secrets: inherit
    with:
      environment: production
      provider: digitalocean
  build:
    uses: bn-digital/docker/.github/workflows/build-images.yml@latest
    secrets: inherit
    with:
      environment: production
  deploy:
    needs:
      - provision
      - build
    uses: bn-digital/helm/.github/workflows/deploy-charts.yml@latest
    secrets: inherit
    with:
      environment: production
      version: ${{ github.event.release.tag_name }}
      domain: ${{ github.event.repository.name }}.bndigital.ai