---
name: Staging Deployment
on:
  workflow_dispatch: {}
  push:
    branches:
      - latest
    paths-ignore:
      - 'helmfile.*'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.git*'
      - '.dockerignore'
      - '.github/**'

jobs:
  secrets:
    uses: bn-digital/vault/.github/workflows/import-secrets.yml@latest
    secrets: inherit
  build:
    needs: [ secrets ]
    uses: bn-digital/docker/.github/workflows/build-images.yml@latest
    secrets: inherit
  deploy:
    needs: [ build ]
    uses: bn-digital/helm/.github/workflows/deploy-charts.yml@latest
    secrets: inherit
