---
name: Deployment
on:
  workflow_dispatch: {}
  push:
    branches:
      - latest
    paths:
      - '.github/workflows/deployment.yml'
      - 'skaffold.yaml'
      - 'helmfile.*'
      - '**/*/.env.*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'yarn.lock'
      - 'packages/website/public/**/*'
      - 'packages/website/src/**/*'
      - 'packages/cms/config/**/*'
      - 'packages/cms/src/**/*'

jobs:
  deploy:
    needs: [ secrets ]
    if: github.events.pull_request.merged || github.event_name == 'workflow_dispatch'
    uses: bn-digital/helm/.github/workflows/deploy-charts.yml@optimize-delivery
    secrets: inherit
