name: Deploy
on:
  workflow_dispatch: { }
  push:
    branches:
      - latest
    paths:
      - ".github/workflows/deploy.yml"
      - "skaffold.yaml"
      - "**/*/.env.*"
      - "**/*/Dockerfile"
      - "**/*/package.json"
      - "packages/cms/src/**/*"
      - "packages/website/src/**/*"
      - "packages/cms/config/**/*"

env:
  APP_NAME: ${{ github.event.repository.name }}
  APP_ENV: staging
  DOMAIN: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  analysis:
    name: Code analysis
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Sonar scanner
        uses: sonarsource/sonarqube-scan-action@v1.0.0

  ci:
    name: CI Pipeline
    runs-on: self-hosted
    environment:
      name: staging
      url: https://app.bndigital.dev
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          method: github
          url: ${{ env.VAULT_ENDPOINT }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/bndigital/${{ env.APP_ENV }}/kubernetes cluster | KUBERNETES_CLUSTER ;
            infrastructure/data/bndigital/${{ env.APP_ENV }}/digitalocean token | DIGITALOCEAN_TOKEN ;
            infrastructure/data/bndigital/${{ env.APP_ENV }}/registry docker-username | DOCKER_USERNAME ;
            infrastructure/data/bndigital/${{ env.APP_ENV }}/registry docker-password | DOCKER_PASSWORD ;
            infrastructure/data/bndigital/${{ env.APP_ENV }}/sonarqube host | SONAR_HOST_URL ;
            infrastructure/data/bndigital/${{ env.APP_ENV }}/sonarqube token | SONAR_TOKEN ;

      - name: Setup DigitalOcean cli
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_TOKEN }}

      - name: Configure Kubernetes context
        run: doctl kubernetes cluster kubeconfig save ${{ env.KUBERNETES_CLUSTER }} --set-current-context

      - name: Release Helm charts
        uses: hiberbee/github-action-helm@1.10.0
        with:
          helmfile: apply