name: Deployment
on:
  push:
    branches:
      - latest
      - main
      - master
    paths:
      - '.github/workflows/continuous-deployment.yml'
      - 'skaffold.yaml'
      - 'helmfile.*'
      - '**/*/.env.*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'yarn.lock'
      - 'packages/website/public/**/*'
      - 'packages/website/src/**/*'
      - 'packages/cms/config/**/*'
      - 'packages/cms/database/**/*'
      - 'packages/cms/public/**/*'
      - 'packages/cms/src/**/*'

jobs:
  secrets:
    uses: bn-digital/vault/.github/workflows/import-secrets.yml@latest
    secrets: inherit
  deploy:
    needs: [ secrets ]
    uses: bn-digital/helm/.github/workflows/deploy-charts.yml@latest
    secrets: inherit
  test:
    needs: [ deploy ]
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          target: test
          tags: ${{ github.event.repository.name }}/website:latest
          build-args: name=${{ github.event.repository.name }}