name: Docker
on:
  push:
    paths:
      - .github/workflows/docker.yml
      - lerna.json
      - package.json
      - yarn.lock
      - .yarnrc.yml
      - Dockerfile
env:
  DOCKER_BUILDKIT: 1
jobs:
  setup:
    name: Docker env setup
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-latest:
    name: NodeJS latest version
    needs: [setup]
    runs-on: ubuntu-20.04
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          tags: |
            bndigital/nodejs:15
            bndigital/nodejs:latest
          build-args: |
            version=15
  build-lts:
    name: NodeJS LTS version
    needs: [ setup ]
    runs-on: ubuntu-20.04
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          build-args: |
            version=14
          tags: |
            bndigital/nodejs:14
            bndigital/nodejs:lts
