name: Import Vault secrets
on:
  workflow_call:
    inputs:
      secrets:
        required: true
        type: string

jobs:
  vault:
    name: Import Vault secrets
    runs-on: self-hosted
    steps:
      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ secrets.VAULT_ENDPOINT }}
          githubToken: ${{ secrets.GH_TOKEN }}
          secrets: ${{ inputs.secrets }}
