---
name: Integration
on:
  pull_request:
    paths:
      - '.github/workflows/integration.yml'
      - 'skaffold.yaml'
      - 'helmfile.*'
      - '**/*/.env.*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'yarn.lock'
      - 'packages/*/public/**/*'
      - 'packages/*/src/**/*'
      - 'packages/*/config/**/*'
      - 'packages/*/database/**/*'

jobs:
  secrets:
    uses: bn-digital/vault/.github/workflows/import-secrets.yml@latest
    secrets: inherit
  provision:
    needs: [ secrets ]
    uses: bn-digital/pulumi/.github/workflows/provision-infrastructure.yml@latest
    secrets: inherit
    with:
      environment: staging
  build:
    needs: [ provision ]
    uses: bn-digital/docker/.github/workflows/build-images.yml@latest
    secrets: inherit
