name: Secrets
on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    paths: 
      - .github/workflows/secrets.yml
jobs:
  sync:
    name: Secrets sync
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            GH_*
            SPACES_*
            DIGITALOCEAN_*
            DOCKER_*
            DOCKERHUB_*
          REPOSITORIES: |
            ${{ github.repository_owner }}/*
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CONCURRENCY: 10
