name: Secrets
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  sync:
    name: Secrets sync
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action
        with:
          SECRETS: |
            ^GH_$
            ^SPACES_$
            ^DIGITALOCEAN_$
            ^DOCKER_$
            ^DOCKERHUB_$
          REPOSITORIES: |
            ${{ github.repository }}
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SECRETS }}
          CONCURRENCY: 10
