name: Secrets
on:
  push:
    paths:
      - .github/workflows/secrets.yml

env:
  VAULT_ENDPOINT: http://vault.infrastructure.svc.cluster.local:8200
  SKAFFOLD_DEFAULT_REPO: http://harbor-registry.infrastructure.svc.cluster.local:5000

jobs:
  sync:
    name: Infrastructure secrets sync
    runs-on: self-hosted
    steps:
      - name: Set secrets from this repo and organization
        uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            VAULT_ENDPOINT
          REPOSITORIES: |
            ${{ github.repository }}
          DRY_RUN: false
          GITHUB_TOKEN: ${{ github.token }}
        env:
          VAULT_ENDPOINT: ${{ env.VAULT_ENDPOINT }}