name: Secrets
on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    paths: 
      - .github/workflows/secrets.yml
jobs:
  sync:
    name: Secrets sync
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            GH_TOKEN
            DOCKER_REGISTRY
            DOCKER_USERNAME
            DOCKER_PASSWORD
            DOCKERHUB_USERNAME
            DOCKERHUB_TOKEN
            DIGITALOCEAN_TOKEN
          REPOSITORIES: |
            ${{ github.repository_owner }}/*
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CONCURRENCY: 10
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
