name: Secrets
on:
  push:
    paths:
      - .github/workflows/secrets.yml

jobs:
  sync:
    name: Secrets sync
    runs-on: self-hosted
    steps:
      - name: Execute organization secrets action
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'bn-digital',
              'infrastructure',
              'workflows/secrets.yaml',
              'latest',
            });