---
name: Transfer
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: staging
        description: |
          Environment to transfer to.
          Warning: that will purge target environment database and all related CMS data!
        options:
          - "development ➔ staging"
          - "staging ➔ production"

jobs:
  strapi-transfer:
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup CMS
        env:
          YARN_NM_HOISTING_LIMITS: workspaces
        run: |
          yarn workspaces focus @${{ github.event.repository.name }}/cms

      - name: Staging DB transfer
        if: ${{ inputs.environment == 'development ➔ staging' }}
        working-directory: packages/cms
        run: |
          NODE_ENV=development yarn strapi transfer --to=https://${{ github.event.repository.name }}.bndigital.dev/admin --to-token=${{ secrets.STRAPI_STAGING_TRANSFER_TOKEN }} --force
